---
- name: check if beehive is already installed
  stat:
    path: /usr/local/sbin/beehive
  register: beehive_exists

- name: Get beehive release
  get_url:                                                           
    url: https://github.com/muesli/beehive/releases/download/v0.3.2/beehive_0.3.2_Linux_armv6.tar.gz
    dest: /home/pi/beehive.tar.gz
  when: beehive_exists.stat.exists == False

- name: create beehive release dir
  file:
    path: /home/pi/beehive_tgz
    state: directory
  when: beehive_exists.stat.exists == False

- name: untar beehive release
  unarchive:                                                    
    src: /home/pi/beehive.tar.gz
    dest: /home/pi/beehive_tgz
    remote_src: yes
  when: beehive_exists.stat.exists == False

- name: Copy beehive executable to the right path
  copy: 
    remote_src: yes 
    src: /home/pi/beehive_tgz/beehive 
    dest: /usr/local/sbin
  when: beehive_exists.stat.exists == False
  become: yes

- name: set beehive permissions
  file:                                                    
    path: /usr/local/sbin
    mode: a+rx
  when: beehive_exists.stat.exists == False
  become: yes

- name: delete beehive temporary elements
  file:                                                    
    path: "{{files}}"
    state: absent
  when: beehive_exists.stat.exists == False
  vars:
    files:
      - /home/pi/beehive_tgz
      - /home/pi/beehive.tar.gz

- name: make sure beehive config fir exists
  stat:
    path: /home/pi/beehive
    state: directory


# beehive run command is "beehive -canonicalurl http://192.168.0.4:8181 -bind :8181"