---
ansible_user: "pi"
# ansible_ssh_private_key_file: "keys/id_rsa"
# dbs_ssh_pubkey: "{{ lookup('file', 'keys/id_rsa.pub') }}"

dbs_set_hostname: true
dbs_set_locale: true
dbs_set_timezone: true
dbs_set_ntp: true
dbs_hostname: "{{ inventory_hostname }}"
dbs_default_locale: "fr_FR.UTF-8"
dbs_locales:
  - "en_US.UTF-8"
  - "fr_FR.UTF-8"
dbs_timezone: "Europe/Paris"

dbs_ntp_hosts:
  - "0.fr.pool.ntp.org"
  - "1.fr.pool.ntp.org"
  - "2.fr.pool.ntp.org"
  - "3.fr.pool.ntp.org"
dbs_ntp_pkg: "ntp"

dbs_groups: []

dbs_users: False

dbs_apt_default_host: "raspbian.raspberrypi.org"
dbs_apt_components: "buster main contrib non-free rpi"

script_install_path: "/home/pi"
