---
- name: Add Docker debian repository
  deb822_repository:
    name: Docker
    state: present
    uris: https://download.docker.com/linux/ubuntu
    suites: "{{ansible_distribution_release}}"
    signed_by:  https://download.docker.com/linux/ubuntu/gpg
    components:
      - stable

- name: Install Docker packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin

- name: Ensure group "docker" exists with correct gid
  ansible.builtin.group:
    name: docker
    state: present

- name: "Adding users"  
  user:
    name: "{{ item }}"
    groups: docker
    append: yes
  loop:
    - "{{ansible_user}}"
    - docker

- name: Install Guerite
  become: yes
  become_user: "{{ansible_user}}"
  community.docker.docker_container:
    name: guerite
    image: ghcr.io/rcarmo/guerite
    state: started
    restart_policy: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      traefik.enable: "false"
    env:
      GUERITE_LOG_LEVEL: INFO
      GUERITE_PRUNE_CRON: docker image prune -f

- name: Create Traefik configuration file
  become: yes
  copy:
    dest: /etc/traefik.yml
    content: |
      # traefik.yml
      api:
        insecure: true
      entryPoints:
        web:
          address: ":80"
      providers:
        docker: {}
      experimental:
        plugins:
            rewritebody:
                moduleName: "github.com/traefik/plugin-rewritebody"
                version: "v0.3.1"

- name: Install Traefik
  become: yes
  become_user: "{{ansible_user}}"
  community.docker.docker_container:
    ports:
      - "{{docker_input}}:80"
      - "8080:8080"
    volumes:
      - "/etc/traefik.yml:/etc/traefik/traefik.yml"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/var/log:/logs:rw"
    image: docker.io/traefik:v3.6
    name: traefik

- name: Install dockpeek
  become: yes
  become_user: "{{ansible_user}}"
  community.docker.docker_container:
    name: dockpeek
    image: docker.io/dockpeek/dockpeek:latest
    state: started
    restart_policy: unless-stopped
    env:
      SECRET_KEY: "{{DOCKPEEK_SECRET}}"
      USERNAME: "{{DOCKPEEK_ADMIN_MAIL}}"
      PASSWORD: "{{DOCKPEEK_ADMIN_PASS}}"
    ports:
      - "3420:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels: 
    # Of course I want to have that container auto-updated
      guerite.update: "*/10 * * * * "
      traefik.http.routers.dockpeek.rule: "PathPrefix(`/dockpeek/`)"
      traefik.http.middlewares.dockpeek.stripprefix.prefixes: "/dockpeek"
      traefik.http.routers.dockpeek.middlewares: "dockpeek@docker"


#- name: Install reproxy
#  become: yes
#  become_user: "{{ansible_user}}"
#  community.docker.docker_container:
#    name: reproxy
#    image: ghcr.io/umputun/reproxy
#    state: started
#    restart_policy: unless-stopped
#    ports:
#      - "{{docker_input}}:8080"
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#    labels: 
#    # Of course I want to have that container auto-updated
#      guerite.update: "*/10 * * * * "
#    command: --docker.enabled --docker.auto

- name: Make sure we have the .local/bin folder
  ansible.builtin.file:
    path: "{{local_bin_folder}}"
    state: directory
  become: true
  become_user: "{{ansible_user}}"

- name: Install ctop
  copy:
    content: |
      #!/bin/sh
      docker run --rm -ti --name=ctop --volume /var/run/docker.sock:/var/run/docker.sock:ro  quay.io/vektorlab/ctop:latest
    mode: '0750'
    dest: "{{local_bin_folder}}/ctop"
  become: true
  become_user: "{{ansible_user}}"

- name: Install Ponysay
  copy:
    content: |
      #!/bin/sh
      docker run -ti --rm mpepping/ponysay $@
    mode: '0750'
    dest: "{{local_bin_folder}}/ponysay"
  become: true
  become_user: "{{ansible_user}}"
