---
- name: Add Docker debian repository
  deb822_repository:
    name: Docker
    state: present
    uris: https://download.docker.com/linux/ubuntu
    suites: "{{ansible_distribution_release}}"
    signed_by:  https://download.docker.com/linux/ubuntu/gpg
    components:
      - stable

- name: Install Docker packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin

- name: Ensure group "docker" exists with correct gid
  ansible.builtin.group:
    name: docker
    state: present

- name: "Adding users"  
  user:
    name: "{{ item }}"
    groups: docker
    append: yes
  loop:
    - "{{ansible_user}}"
    - docker

- name: Install Guerite
  become: yes
  become_user: "{{ansible_user}}"
  community.docker.docker_container:
    name: guerite
    image: ghcr.io/rcarmo/guerite
    state: started
    restart_policy: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      traefik.enable: "false"
    env:
      GUERITE_LOG_LEVEL: INFO
      GUERITE_PRUNE_CRON: docker image prune -f

- name: Create Traefik configuration file
  become: yes
  copy:
    dest: /etc/traefik.yml
    content: |
      # traefik.yml
      api:
        insecure: true
      certificatesResolvers:
        letsencrypt:
          acme:
            email: "admin@nicolas-delsaux.hd.free.fr"  # Email pour les notifications
            storage: /etc/traefik/acme.json   # Où stocker les certificats
            caServer: "https://acme-v02.api.letsencrypt.org/directory"
            httpChallenge:
              entryPoint: web                 # Entrypoint pour le challenge HTTP
      entryPoints:
        web:
          address: ":80"
          http:
            redirections:
              entryPoint:
                to: websecure
                scheme: https
                permanent: true
        websecure:
          address: ":443"
          http:
            tls: true
      providers:
        docker: {}
      log:
        filePath: "/var/log/traefik/standard.log"
        level: INFO
        compress: true
      accessLog:
        filePath: "/var/log/traefik/access.log"
        # JSON format
        format: json
      experimental:
        plugins:
          redirectLocation:
            modulename: "github.com/SchmitzDan/traefik-plugin-redirect-location"
            version: "v0.0.1" #replace with newest version
          rewriteHeaders:
            modulename: "github.com/XciD/traefik-plugin-rewrite-headers"
            version: "v0.0.4"
          rewritebody:
              moduleName: "github.com/traefik/plugin-rewritebody"
              version: "v0.3.1"
          fullUrlRewrite:
            moduleName: "github.com/e-flux-platform/full-url-rewrite-traefik-plugin"
            version: "v0.0.6"
- name: Create Docker bridge to the internet network
  become: yes
  become_user: "{{ansible_user}}"
  community.docker.docker_network:
    name: bridge_to_the_internet
- name: Create Let's encrypt configuration folder tree
  become: yes
  become_user: "{{ansible_user}}"
  file:
    owner: "{{ansible_user}}"
    path: "{{home_folder}}/.config/traefik/letsencrypt"
    state: directory

#- name: Create Let's encrypt configuration file
#  become: yes
#  become_user: "{{ansible_user}}"
#  file:
#    owner: "{{ansible_user}}"
#    path: "{{home_folder}}/.config/traefik/letsencrypt/acme.json"
#    state: touch
#    mode: '0600'

- name: Install Traefik
  become: yes
  become_user: "{{ansible_user}}"
  community.docker.docker_container:
    name: traefik
    image: docker.io/traefik:v3.6
    restart_policy: always
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    networks:
      - name: "bridge_to_the_internet"
    volumes:
      - "/etc/traefik.yml:/etc/traefik/traefik.yml"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/var/log:/var/log:rw"
      - "~/.config/traefik/letsencrypt:/letsencrypt"
    labels:
      guerite.update: "*/10 * * * * "
      
- name: Make sure we have the traefik-manager folder
  ansible.builtin.file:
    path: "{{folders}}"
    state: directory
  become: true
  become_user: "{{ansible_user}}"
  vars:
    folders:
    - "{{home_folder}}/traefik-manager"
    - "{{home_folder}}/traefik-manager/config"
    - "{{home_folder}}/traefik-manager/backups"

- name: Install traefik-manager
  become: yes
  become_user: "{{ansible_user}}"
  community.docker.docker_container:
    name: traefik-manager
    image: ghcr.io/chr0nzz/traefik-manager:latest
    restart_policy: "unless-stopped"
    ports:
      - "5000:5000"
    networks:
      - name: "bridge_to_the_internet"
    env:
      COOKIE_SECURE: "false"
      ACCESS_LOG_PATH: "/var/log/traefik/access.log"
      STATIC_CONFIG_PATH: "/etc/traefik/traefik.yml"
    volumes:
      - "/etc/traefik.yml:/etc/traefik/traefik.yml"
      - "/var/log:/var/log:rw"
      - "{{home_folder}}/traefik-manager/config:/app/config"
      - "{{home_folder}}/traefik-manager/backups:/app/backups"
    labels:
      guerite.update: "*/10 * * * * "

- name: Make sure we have the .local/bin folder
  ansible.builtin.file:
    path: "{{local_bin_folder}}"
    state: directory
  become: true
  become_user: "{{ansible_user}}"

- name: Install ctop
  copy:
    content: |
      #!/bin/sh
      docker run --rm -ti --name=ctop --volume /var/run/docker.sock:/var/run/docker.sock:ro  quay.io/vektorlab/ctop:latest
    mode: '0750'
    dest: "{{local_bin_folder}}/ctop"
  become: true
  become_user: "{{ansible_user}}"

- name: Install Ponysay
  copy:
    content: |
      #!/bin/sh
      docker run -ti --rm mpepping/ponysay $@
    mode: '0750'
    dest: "{{local_bin_folder}}/ponysay"
  become: true
  become_user: "{{ansible_user}}"
