---
- name: Create Traefik configuration file
  become: yes
  copy:
    src: traefik/traefik.yml
    dest: /etc/traefik.yml
- name: Create Docker bridge to the internet network
  become: yes
  become_user: "{{ansible_user}}"
  community.docker.docker_network:
    name: bridge_to_the_internet
- name: Create Let's encrypt configuration folder tree
  become: yes
  become_user: "{{ansible_user}}"
  file:
    owner: "{{ansible_user}}"
    path: "{{home_folder}}/.config/traefik/letsencrypt"
    state: directory

- name: Install Traefik
  become: yes
  become_user: "{{ansible_user}}"
  community.docker.docker_container:
    name: traefik
    image: docker.io/traefik:v3.6
    restart_policy: always
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    networks:
      - name: "bridge_to_the_internet"
    volumes:
      - "/etc/traefik.yml:/etc/traefik/traefik.yml"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/var/log:/var/log:rw"
      - "~/.config/traefik/letsencrypt:/letsencrypt"
    labels:
      guerite.update: "{{guerite_crontab}}"
# Option added for traefik to see nextcp2 container running on host network
    etc_hosts:
      host.docker.internal: "host-gateway"
