---
- name: Make sure we have the traefik-manager folder
  ansible.builtin.file:
    path: "{{folders}}"
    state: directory
  become: true
  become_user: "{{ansible_user}}"
  vars:
    folders:
    - "{{home_folder}}/traefik-manager"
    - "{{home_folder}}/traefik-manager/config"
    - "{{home_folder}}/traefik-manager/backups"

- name: Install traefik-manager 🐳
  become: yes
  become_user: "{{ansible_user}}"
  community.docker.docker_container:
    name: traefik-manager
    image: ghcr.io/chr0nzz/traefik-manager:latest
    restart_policy: "unless-stopped"
    ports:
      - "5000:5000"
    networks:
      - name: "bridge_to_the_internet"
    env:
      COOKIE_SECURE: "true"
      ACCESS_LOG_PATH: "/var/log/traefik/access.log"
      STATIC_CONFIG_PATH: "/etc/traefik/traefik.yml"
      TRAEFIK_API_URL: "http://traefik:8080"
    volumes:
      - "/etc/traefik.yml:/etc/traefik/traefik.yml"
      - "/var/log:/var/log:rw"
      - "{{home_folder}}/traefik-manager/config:/app/config"
      - "{{home_folder}}/traefik-manager/backups:/app/backups"
    labels:
      guerite.update: "{{guerite_crontab}}"
      traefik.enable: "true"
      traefik.http.routers.traefikManager.entrypoints: "websecure"
      traefik.http.routers.traefikManager.tls: "true"
      traefik.http.routers.traefikManager.tls.certresolver: "letsencrypt" 
      traefik.http.routers.traefikManager.rule: "Host(`nicolas-delsaux.hd.free.fr`) && PathPrefix(`/traefik-manager`)"
      traefik.http.routers.traefikManager.middlewares: "traefikManager@docker"
      traefik.http.middlewares.traefikManager-prefix.stripprefix.prefixes: "/traefik-manager"
      traefik.http.middlewares.traefikManager-rewrite-body.plugin.rewrite-body.rewrites[0].regex: >-
        (["'\x60])/(api|login|static)
      traefik.http.middlewares.traefikManager-rewrite-body.plugin.rewrite-body.rewrites[0].replacement: >-
        ${1}/traefik-manager/${2}
      traefik.http.middlewares.traefikManager-rewrite-body.plugin.rewrite-body.monitoring.methods[0]: "GET"
      traefik.http.middlewares.traefikManager-rewrite-body.plugin.rewrite-body.monitoring.types[0]: "text/html"
      traefik.http.middlewares.traefikManager-rewrite-body.plugin.rewrite-body.monitoring.types[1]: "application/javascript"
      traefik.http.middlewares.traefikManager-rewrite-body.plugin.rewrite-body.monitoring.types[2]: "*/*"
      traefik.http.middlewares.traefikManager-rewrite-location.plugin.redirectLocation.default: "true"
      traefik.http.middlewares.traefikManager-headers.headers.customresponseheaders.X-deployed-by-ansible: "v6"
      traefik.http.middlewares.traefikManager.chain.middlewares: "traefikManager-rewrite-location,traefikManager-prefix,traefikManager-rewrite-body, traefikManager-headers"
    restart: true
