---
- name: Make sure config folder exists
  file:
    path: /etc/komga
    state: directory

- name: Make sure download folder exists
  file:
    path: "{{home_folder}}/komga"
    state: directory
    owner: "{{ansible_user}}"
  become: yes
  become_user: "{{ansible_user}}"

- name: Install Komga
  become: yes
  become_user: "{{ansible_user}}"
  community.docker.docker_container:
    name: komga
    image: gotson/komga
    state: started
    restart_policy: unless-stopped
    networks:
      - name: "bridge_to_the_internet"
    env:
      TZ: "Europe/Paris"
      SERVER_SERVLET_CONTEXT_PATH: "/komga"
    volumes:
      - "/etc/komga:/config"
      - "{{home_folder}}/komga:/data"
    labels: 
    # Of course I want to have that container auto-updated
      guerite.update: "*/10 * * * * "
      traefik.enable: "true"
      traefik.http.routers.komga.entrypoints: "websecure"
      traefik.http.routers.komga.tls: "true"
      traefik.http.routers.komga.tls.certresolver: "letsencrypt" 
      traefik.http.routers.komga.rule: "Host(`nicolas-delsaux.hd.free.fr`) && PathPrefix(`/komga`)"
      traefik.http.routers.komga.middlewares: "komga@docker"
#      traefik.http.middlewares.komga-prefix.stripprefix.prefixes: "/komga"
#      traefik.http.middlewares.komga-rewrite-body.plugin.rewritebody.rewrites[0].regex: "\"/"
#      traefik.http.middlewares.komga-rewrite-body.plugin.rewritebody.rewrites[0].replacement: "\"/komga/"
#      traefik.http.middlewares.komga-rewrite-location.plugin.redirectLocation.default: "true"
      traefik.http.middlewares.komga.chain.middlewares: ""
