---
- name: Install pykeepass
  ansible.builtin.pip: 
    name: pykeepass
  delegate_to: localhost 

- name: Install Kavita
  include_tasks: kavita.yml

- name: Install Transmission
  include_tasks: transmission.yml

#- name: Configure shell
#  include_tasks: shell.yml
