---
- name: Install pykeepass
  ansible.builtin.pip: 
    name: pykeepass
  delegate_to: localhost 

- name: Install Kavita
  include_tasks: kavita.yml

- name: Install BubbleUPnPServer
  include_tasks: bubble.yml

- name: Install Transmission
  include_tasks: transmission.yml

- name: Install metube
  include_tasks: metube.yml

- name: Install handbrake
  include_tasks: handbrake.yml

- name: Install gerbera
  include_tasks: gerbera.yml

#- name: Configure shell
#  include_tasks: shell.yml
