---
- name: Make sure we have the nextcp2 folder
  ansible.builtin.file:
    path: "{{folders}}"
    state: directory
  become: true
  become_user: "{{ansible_user}}"
  vars:
    folders:
    - "{{home_folder}}/nextcp2"

- name: Install nextcp2
  become: yes
  become_user: "{{ansible_user}}"
  community.docker.docker_container:
    name: nextcp2
    image: ik6666/nextcp2:latest
    state: started
    restart_policy: unless-stopped
    command: -dataDir /data
    # Yes I run it as root
    user: 0:0
    hostname: nextcp2
    volumes:
      - "{{home_folder}}/nextcp2:/nextcp2_data"
#    network_mode: host
    networks:
      - name: "bridge_to_the_internet"
    env:
      # https://bubblesoftapps.com/nextcp22/docs/docker.html#disabling-all-writing-to-to-disk
      JAVA_TOOL_OPTIONS: '-Xmx2048m -XX:+UseShenandoahGC'
      SERVER_SERVLET_CONTEXT_PATH: /nextcp2
    labels: 
    # Of course I want to have that container auto-updated
      guerite.update: "{{guerite_crontab}}"
      traefik.enable: "true"
      traefik.http.routers.nextcp2.entrypoints: "websecure"
      traefik.http.routers.nextcp2.tls: "true"
      traefik.http.routers.nextcp2.tls.certresolver: "letsencrypt" 
      traefik.http.routers.nextcp2.rule: "Host(`nicolas-delsaux.hd.free.fr`) && PathPrefix(`/nextcp2`)"
      traefik.http.routers.nextcp2.middlewares: "nextcp2@docker"
      traefik.http.services.nextcp2.loadbalancer.server.port: "8085"
      traefik.http.middlewares.nextcp2-prefix.stripprefix.prefixes: "/nextcp2/"
      traefik.http.middlewares.nextcp2-rewrite-location.plugin.redirectLocation.default: "true"
      traefik.http.middlewares.nextcp2-rewrite-body.plugin.rewritebody.rewrites[0].regex: "<base.*>"
      traefik.http.middlewares.nextcp2-rewrite-body.plugin.rewritebody.rewrites[0].replacement: "<base href=\"/nextcp2/\">"
      traefik.http.middlewares.nextcp2.chain.middlewares: "nextcp2-rewrite-body"
