---
- name: install qBitTorrent
  apt:
    name: qbittorrent-nox

- name: create qBitTorrent group
  group:
    name: qbittorrent
    state: present

- name: create qBitTorrent user
  user:
    name: qbittorrent
    groups: qbittorrent
    shell: /sbin/nologin
    append: yes
    state: present
    create_home: yes

- name: Adding user pi to qBitTorrent
  user:
    name: pi
    groups: qbittorrent
    append: true

- name: Copy qBitTorrent systemd service file to server
  template:
    src: qbittorrent.service
    dest: /etc/systemd/system
    owner: root
    group: root

- name: Activate qBitTorrent service
  systemd:
    name: qbittorrent
    state: started
    enabled: yes

- name: Make sure incoming folder is accessible by pi user
  file:
    path: /var/lib/mldonkey/incoming
    mode: 777
    recurse: yes
  become: yes
  become_user: pi

- name: Create crontab entry to make sure incoming files can be easily deleted after copy
  cron:
    name: Make downloaded files freely writable
    hour: "0"
    minute: "0"
    weekday: "5"
    job: "chmod -R ugoa+w /home/pi/incoming/"
  become: yes

- name: Create crontab entry to backup downloaded files
  cron:
    name: Backup mldonkey downloads
    hour: "1"
    minute: "0"
    weekday: "5"
    job: "rsync  --remove-source-files -az --copy-dirlinks --log-file=/home/pi/log/rsync_mldonkey.log /home/pi/incoming admin@192.168.0.2:/share/Download/mldonkey"
  become: yes
  become_user: pi

