---
# Quite sure there is something weird regarding ownership maniuplated by Docker ...
#- name: Make sure incoming folder is accessible by nicolas-delsaux user
#  file:
#    path: "{{home_folder}}/qbittorrent"
#    state: directory
#    owner: "{{ansible_user}}"
#  become: yes
#  become_user: "{{ansible_user}}"

- name: Create crontab entry to make sure incoming files can be easily deleted after copy
  cron:
    name: Make downloaded files freely writable
    hour: "0"
    minute: "0"
    weekday: "5"
    job: "chmod -R ugoa+w {{home_folder}}/qbittorrent"
  become: yes

- name: Create crontab entry to backup downloaded files
  cron:
    name: Backup mldonkey downloads
    hour: "1"
    minute: "0"
    weekday: "5"
    job: "rsync  --remove-source-files -az --copy-dirlinks --log-file={{home_folder}}/log/rsync_mldonkey.log {{home_folder}}/qbittorrent admin@192.168.1.2:/share/Download/mldonkey"
  become: yes
  become_user: "{{ansible_user}}"

- name: Make sure config folder exists
  file:
    path: /etc/qBitTorrent
    state: directory

- name: Install qBittorrent image
  become: yes
  community.docker.docker_container:
    name: qbittorrent
    image: lscr.io/linuxserver/qbittorrent:latest
    state: started
    restart_policy: unless-stopped
    networks:
      - name: "bridge_to_the_internet"
    ports:
      - "6881:6881"
      - "6881:6881/udp"
    env:
      TZ: "Europe/Paris"
      WEBUI_PORT: "8080"
      TORRENTING_PORT: "6881"
      DOCKER_MODS: "ghcr.io/vuetorrent/vuetorrent-lsio-mod:latest"
    volumes:
      - "{{home_folder}}/qbittorrent:/downloads"
      - "/etc/qBitTorrent/:/config"
    labels: 
    # Thanks to https://github.com/qbittorrent/qBittorrent/wiki/Traefik-Reverse-Proxy-for-Web-UI
    # Of course I want to have that container auto-updated
      guerite.update: "*/10 * * * * "
      traefik.enable: "true"
      traefik.http.services.qb.loadbalancer.server.port: "8080"
      traefik.http.routers.qb.entrypoints: "websecure"
      traefik.http.routers.qb.tls: "true"
      traefik.http.routers.qb.tls.certresolver: "letsencrypt" 
      traefik.http.routers.qb.rule: "Host(`nicolas-delsaux.hd.free.fr`) && PathPrefix(`/qBitTorrent`)"
      traefik.http.routers.qb.middlewares: "qb@docker"
      traefik.http.middlewares.qb-headers.headers.customrequestheaders.X-Frame-Options: "SAMEORIGIN"
      traefik.http.middlewares.qb-headers.headers.customrequestheaders.Referer: ""
      traefik.http.middlewares.qb-headers.headers.customrequestheaders.Origin: ""
      traefik.http.middlewares.qb-redirect.redirectregex.regex: "^(.*)/qBitTorrent$$"
      traefik.http.middlewares.qb-redirect.redirectregex.replacement: "$$1/qBitTorrent/"
      traefik.http.middlewares.qb-prefix.stripprefix.prefixes: "/qBitTorrent"
      traefik.http.middlewares.qb-rewrite-body.plugin.rewritebody.rewrites[0].regex: "qBittorrent WebUI"
      traefik.http.middlewares.qb-rewrite-body.plugin.rewritebody.rewrites[0].replacement: "pouet"
      traefik.http.middlewares.qb.chain.middlewares: "qb-rewrite-body,qb-prefix,qb-headers"
