- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest
    cache_valid_time: 3600

- name: Upgrade distribution
  apt:
    upgrade: dist
    cache_valid_time: 3600

- name: Remove useless packages from the cache
  apt:
    autoclean: yes

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes
