---
- name: At install, make sure we use the correct timezome
  timezone:
    name: Europe/Paris

- name: Make sure time is refreshed regularly
  cron:
    name: Force refresh of ntp time
    hour: "1"
    minute: "0"
    weekday: "1"
    job: "systemctl restart systemd-timesyncd.service"
  become: yes

- name: Disable useless services
  include_tasks: disable_services.yml

#- name: Process APT
#  include_tasks: apt.yml
#
#- name: check if package is installed
#  package:
#    name: dphys-swapfile
#    state: present
#  check_mode: true
#  register: dphys_swapfile_check
## See https://stackoverflow.com/a/46630866/15619
#- name: Uninstall dphys_swapfile and swap
#  include_tasks: uninstall_swap.yml
#  when: not dphys_swapfile_check.changed==true
#
#- name: Put logs in ramfs
#  include_tasks: logs_in_ramfs.yml