---
- name: Make sure we have the Grav folder
  ansible.builtin.file:
    path: "{{folders}}"
    state: directory
  become: true
  become_user: "{{ansible_user}}"
  vars:
    folders:
    - "{{home_folder}}/grav/config"

- name: Install Grav image
  become: yes
  become_user: "{{ansible_user}}"
  community.docker.docker_container:
    name: poecile
    image: lscr.io/linuxserver/grav:latest
    state: started
    restart_policy: unless-stopped
    networks:
      - name: "bridge_to_the_internet"
    env:
      TZ: "Europe/Paris"
    labels: 
    # Of course I want to have that container auto-updated
      guerite.update: "{{guerite_crontab}}"
      traefik.enable: "true"
      traefik.http.routers.grav.entrypoints: "websecure"
      traefik.http.routers.grav.tls: "true"
      traefik.http.routers.grav.tls.certresolver: "letsencrypt" 
      traefik.http.routers.grav.rule: "Host(`nicolas-delsaux.hd.free.fr`) && PathPrefix(`/blog`)"
      traefik.http.routers.grav.middlewares: "grav@docker"
      traefik.http.middlewares.grav-prefix.stripprefix.prefixes: "/blog"
      traefik.http.middlewares.grav-rewrite-body.plugin.rewritebody.rewrites[0].regex: "\"/"
      traefik.http.middlewares.grav-rewrite-body.plugin.rewritebody.rewrites[0].replacement: "\"/blog/"
      traefik.http.middlewares.grav-rewrite-body.plugin.rewritebody.rewrites[1].regex: ": /admin"
      traefik.http.middlewares.grav-rewrite-body.plugin.rewritebody.rewrites[1].replacement: ": /blog/admin"
      traefik.http.middlewares.grav-rewrite-location.plugin.redirectLocation.default: "true"
      traefik.http.middlewares.grav.chain.middlewares: "grav-prefix,grav-rewrite-location,grav-rewrite-body"
    volumes:
      - "{{home_folder}}/grav/config:/config"
