- name: Now install certbot-auto
  apt:
    name: certbot

- name: And the dedicated Apache plugin
  apt:
    name: python-certbot-apache
  
- name: Check if certificate already exists
  stat:
    path: /etc/letsencrypt/live/nicolas-delsaux.hd.free.fr/fullchain.pem
  register: certificate_exists

- name: Run certbot
  command:
  args:
    argv:
      - certbot
      - -d nicolas-delsaux.hd.free.fr
      - --apache
      - -n
      - --agree-tos
      - -m nicolas.delsaux@gmx.fr
  when: certificate_exists.stat.exists == False

- name: Automate certificate renewall
  cron:
    name: Renew certificate
    hour: "0"
    minute: "10"
    weekday: "1"
    job: "certbot renew"
  become: yes


