---
- name: Install required packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - sshpass
    - git
    - acl

- name: Install pykeepass
  ansible.builtin.pip: 
    name: pykeepass
  delegate_to: localhost 
#- name: Remove Apache/PHP
#  include_tasks: no_apache_php.yml

- name: Add nicolas-delsaux user to www-data group
  user:
    name: nicolas-delsaux
    shell: /bin/bash
    groups: www-data
    append: yes

- name: Making /var/www accessible
  file:
    path: /var/www/
    group: www-data
    owner: www-data
    mode: u=rwx,g=rwx,o=rwx
    recurse: yes

- name: Install Shaarli
  include_tasks: shaarli.yml

- name: Install rss-bridge
  include_tasks: rss-bridge.yml

#- name: Install Tweetledee
#  include_tasks: tweetledee.yml

- name: Install mastodon-rss
  include_tasks: mastodon-rss.yml

#- name: Install wordpress
#  include_tasks: wordpress.yml
#
- name: Install grav
  include_tasks: grav.yml