---
- name: Install required packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - composer
    - yarn
    - git

- name: Install Apache/PHP
  include_tasks: php.yml

- name: Add pi user to www-data group
  user:
    name: pi
    shell: /bin/bash
    groups: www-data
    append: yes

- name: Making /var/www accessible
  file:
    path: /var/www/
    group: www-data
    owner: www-data
    mode: u=rwx,g=rwx,o=rwx
    recurse: yes

- name: Make sure /var/log/apache2 is always present (because it is removed due to tmpfs)
  cron:
    name: Recreate apache log folder
    special_time: reboot
    job: "mkdir /var/log/apache2 && chown www-data:www-data /var/log/apache2"
  become: yes


- name: Create simple php template file
  template:
    src: index.php.j2
    dest: /var/www/html/state.php
    group: www-data
    owner: www-data
    mode: 0777

- name: Install Let's Encrypt
  include_tasks: letsencrypt.yml

- name: Install Shaarli
  include_tasks: shaarli.yml

- name: Install rss-bridge
  include_tasks: rss-bridge.yml

- name: Install Tweetledee
  include_tasks: tweetledee.yml