---
- name: Install required packages
  apt:
    name: "{{ packages }}"
    default_release: stretch
  vars:
    packages:
      - apache2
      - apache2-utils
      - php7.0
      - php7.0-curl
      - php7.0-gd
      - php7.0-fpm
      - php7.0-cli
      - php7.0-opcache
      - php7.0-json
      - php7.0-mbstring
      - php7.0-xml
      - php7.0-zip
#      - php7.0-mysql
      - libapache2-mod-php7.0

- name: Add pi user to www-data group
  user:
    name: pi
    shell: /bin/bash
    groups: www-data
    append: yes

- name: Making /var/www accessible
  file:
    path: /var/www/
    group: www-data
    owner: www-data
    mode: u=rwx,g=rwx,o=rwx
    recurse: yes

- name: Make sure /var/log/apache2 is always present (because it is removed due to tmpfs)
  cron:
    name: Recreate apache log folder
    special_time: reboot
    job: "mkdir /var/log/apache2 && chown www-data:www-data /var/log/apache2"
  become: yes


- name: Create simple php template file
  template:
    src: index.php.j2
    dest: /var/www/html/state.php
    group: www-data
    owner: www-data
    mode: 0777

- name: Install Let's Encrypt
  include_tasks: letsencrypt.yml

- name: Install Shaarli
  include_tasks: shaarli.yml

- name: Install rss-bridge
  include_tasks: rss-bridge.yml

- name: Install Tweetledee
  include_tasks: tweetledee.yml