- name: Install php repository GPG key
  apt_key:
    url: https://packages.sury.org/php/apt.gpg

- name: Install php repository
  apt_repository:
    repo: deb https://packages.sury.org/php/ {{raspbian_version}} main
    state: present

# Time to use https://www.tal.org/tutorials/setup-php-7-or-8-apache-raspberry-pi
- name: Install required packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - ca-certificates
      - apache2
      - apache2-utils
      - php{{php_version}}
      - php{{php_version}}-curl
      - php{{php_version}}-gd
      - php{{php_version}}-fpm
      - php{{php_version}}-cli
      - php{{php_version}}-opcache
#      - php{{php_version}}-json
      - php{{php_version}}-mbstring
      - php{{php_version}}-xml
      - php{{php_version}}-zip
#      - php{{php_version}}-mysql
      - libapache2-mod-fcgid
  ignore_errors: yes

- name: enable apache2 module
  command: a2enmod proxy_fcgi
  become: yes

- name: enable apache2 php conf
  command: a2enconf php{{php_version}}-fpm
  become: yes

- name: enable apache2 service
  command: systemctl start apache2
  become: yes
- name: reload apache2 service
  command: systemctl reload apache2
  become: yes
