# mainly borrowed from https://ayesh.me/Ubuntu-PHP-7.2
- name: Install required packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - apache2
      - apache2-utils
      - php{{php_version}}
      - php{{php_version}}-curl
      - php{{php_version}}-gd
      - php{{php_version}}-fpm
      - php{{php_version}}-cli
      - php{{php_version}}-opcache
      - php{{php_version}}-json
      - php{{php_version}}-mbstring
      - php{{php_version}}-xml
      - php{{php_version}}-zip
#      - php{{php_version}}-mysql
      - libapache2-mod-php{{php_version}}
  ignore_errors: yes

- name: enabled php
  apache2_module: name=php7 state=present
