---
- name: Check if we should download rss-bridge
  stat: 
    path: /var/www/html/rss-bridge
  register: rss_bridge_exists

- name: download rss-bridge
  git:
    repo: https://github.com/Riduidel/rss-bridge.git
    dest: /var/www/html/rss-bridge
    version: live
  when: rss_bridge_exists.stat.exists == False

- name: Check if config is present
  stat: 
    path: /var/www/html/rss-bridge/whitelist.txt
  register: config_exists

- name: Copy data from QNAP
  command:
  args:
    chdir: /var/www/html/rss-bridge
    argv:
      - rsync
      - -r 
      - admin@192.168.0.2:/share/Download/raspberry-server/to_backup/rss-bridge/*
      - /var/www/html/rss-bridge
  become: yes
  become_user: pi
  when: config_exists.stat.exists == False

- name: Make rss-bridge usable by www-data
  file:
    path: /var/www/html/rss-bridge
    group: www-data
    owner: www-data
    mode: 0777
    recurse: yes

- name: Prepare config backup
  file:
    path: /home/pi/to_backup/rss-bridge
    owner: pi
    group: pi
    recurse: true
    state: directory

- name: Immediatly mark config for backup
  file:
    src: /var/www/html/rss-bridge/whitelist.txt
    dest: /home/pi/to_backup/rss-bridge/whitelist.txt
    owner: pi
    group: pi
    state: link
