---
- name: Install required packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - composer
    - yarn
    - git

- name: Check if we should download rss-bridge
  stat: 
    path: /var/www/html/rss-bridge
  register: rss_bridge_exists

- name: download rss-bridge
  git:
    repo: https://github.com/Riduidel/rss-bridge.git
    dest: /var/www/html/rss-bridge
    version: live
  become: yes
  become_user: nicolas-delsaux
  when: rss_bridge_exists.stat.exists == False

- name: Check if config is present
  stat: 
    path: /var/www/html/rss-bridge/whitelist.txt
  become: yes
  become_user: nicolas-delsaux
  register: config_exists

- name: Copy data from QNAP
  command: sshpass -p "{{qnap_password}}" rsync -r "{{ qnap_admin_user }}"@"{{ qnap_server_address }}":/share/Download/raspberry-server/to_backup/rss-bridge/* /var/www/html/rss-bridge
  args:
    chdir: /var/www/html/rss-bridge
  become: yes
  become_user: nicolas-delsaux
  when: config_exists.stat.exists == False

- name: Make rss-bridge usable by www-data
  file:
    path: /var/www/html/rss-bridge
    group: www-data
    owner: www-data
    mode: 0777
    recurse: yes

- name: Prepare config backup
  file:
    path: {{home_folder}}/to_backup/rss-bridge
    owner: nicolas-delsaux
    group: nicolas-delsaux
    recurse: true
    state: directory

- name: Immediatly mark config for backup
  file:
    src: /var/www/html/rss-bridge/whitelist.txt
    dest: {{home_folder}}/to_backup/rss-bridge/whitelist.txt
    owner: nicolas-delsaux
    group: nicolas-delsaux
    state: link
