---
- name: Check if config is present
  stat: 
    path: /var/www/html/Shaarli/data/config.json.php
  register: config_exists

- name: Make Shaarli data usable by www-data
  file:
    path: /var/www/html/Shaarli
    group: www-data
    owner: www-data
    mode: 0777
    recurse: yes
  when: config_exists.stat.exists == False

#- name: Copy data from QNAP
#  command: sshpass -p "{{qnap_password}}" rsync -r "{{ qnap_admin_user }}"@"{{ qnap_server_address }}":/share/Download/raspberry-server/to_backup/Shaarli/data/* /var/www/html/Shaarli/data
#  args:
#    chdir: /var/www/html/Shaarli
#  become: yes
#  become_user: "{{ansible_user}}"
#  when: config_exists.stat.exists == False

- name: Prepare config backup
  file:
    path: "{{home_folder}}/to_backup/Shaarli/"
    owner: nicolas-delsaux
    group: nicolas-delsaux
    recurse: true
    state: directory

- name: Immediatly mark config for backup
  file:
    src: /var/www/html/Shaarli/data
    dest: "{{home_folder}}/to_backup/Shaarli/data"
    owner: nicolas-delsaux
    group: nicolas-delsaux
    state: link

- name: Download mastodon plugin
  git:
    repo: https://github.com/kalvn/shaarli2mastodon/
    dest: /var/www/html/Shaarli/plugins/shaarli2mastodon
    version: v3.0.0
  become: yes
  become_user: www-data
  ignore_errors: true

- name: Install Shaarli base image
  become: yes
  become_user: "{{ansible_user}}"
  community.docker.docker_container:
    name: Shaarli
    image: shaarli/shaarli:latest
    state: started
    restart_policy: unless-stopped
    networks:
      - name: "bridge_to_the_internet"
    labels: 
    # Of course I want to have that container auto-updated
      guerite.update: "{{guerite_crontab}}"
      traefik.enable: "true"
      traefik.http.routers.Shaarli.entrypoints: "websecure"
      traefik.http.routers.Shaarli.tls: "true"
      traefik.http.routers.Shaarli.tls.certresolver: "letsencrypt" 
      traefik.http.routers.Shaarli.rule: "Host(`nicolas-delsaux.hd.free.fr`) && PathPrefix(`/Shaarli`)"
      traefik.http.routers.Shaarli.middlewares: "Shaarli@docker"
      traefik.http.middlewares.Shaarli-prefix.stripprefix.prefixes: "/Shaarli"
      traefik.http.middlewares.Shaarli-rewrite-body.plugin.rewritebody.rewrites[0].regex: "\"/"
      traefik.http.middlewares.Shaarli-rewrite-body.plugin.rewritebody.rewrites[0].replacement: "\"/Shaarli/"
      traefik.http.middlewares.Shaarli-rewrite-location.plugin.redirectLocation.default: "true"
      traefik.http.middlewares.Shaarli.chain.middlewares: "Shaarli-rewrite-body,Shaarli-prefix,Shaarli-rewrite-location"
    volumes:
      - /var/www/html/Shaarli/data:/var/www/shaarli/data 
      - /var/www/html/Shaarli/plugins/:/var/www/shaarli/plugins/