---
- name: Check if we should download Shaarli
  stat: 
    path: /var/www/html/Shaarli/
  register: shaarli_exists

- name: download Shaarli
  git:
    repo: https://github.com/Riduidel/Shaarli.git
    dest: /var/www/html/Shaarli
    version: latest
  become: yes
  become_user: www-data
  when: shaarli_exists.stat.exists == False

- name: Check if composer should run
  stat: 
    path: /var/www/html/Shaarli/vendor
  register: composer_exists

# it will only work with swap enabled !
- name: Update composer dependencies
  command: composer install --no-dev --prefer-dist
  args:
    chdir: /var/www/html/Shaarli
  become: yes
  become_user: www-data
  when: composer_exists.stat.exists == False

- name: Build front-end
  command: make build_frontend
  args:
    chdir: /var/www/html/Shaarli
  become: yes
  become_user: www-data
  when: composer_exists.stat.exists == False

- name: Check if config is present
  stat: 
    path: /var/www/html/Shaarli/data/config.json.php
  register: config_exists

- name: Make Shaarli data usable by www-data
  file:
    path: /var/www/html/Shaarli
    group: www-data
    owner: www-data
    mode: 0777
    recurse: yes
  when: config_exists.stat.exists == False

- name: Copy data from QNAP
  command: sshpass -p "{{qnap_password}}" rsync -r admin@192.168.0.2:/share/Download/raspberry-server/to_backup/Shaarli/data/* /var/www/html/Shaarli/data
  args:
    chdir: /var/www/html/Shaarli
#  become: yes
#  become_user: www-data
  when: config_exists.stat.exists == False

- name: Prepare config backup
  file:
    path: /home/pi/to_backup/Shaarli/
    owner: pi
    group: pi
    recurse: true
    state: directory

- name: Immediatly mark config for backup
  file:
    src: /var/www/html/Shaarli/data
    dest: /home/pi/to_backup/Shaarli/data
    owner: pi
    group: pi
    state: link

- name: Make Shaarli usable by www-data
  file:
    path: /var/www/html/Shaarli
    group: www-data
    owner: www-data
    mode: 0777
    recurse: yes

- name: Download mastodon plugin
  git:
    repo: https://github.com/kalvn/shaarli2mastodon/
    dest: /var/www/html/Shaarli/plugins/shaarli2mastodon
    version: v3.0.0
  become: yes
  become_user: www-data
  ignore_errors: true

- name: Allow override all in Apache main config
  lineinfile:
    firstmatch: true
    state: present
    search_string: 'AllowOverride None'
    insertafter: '<Directory \/var\/www\/>'
    line: '    AllowOverride All'
    path: /etc/apache2/apache2.conf
  become: yes