---
- name: Make sure we have the MariaDB folder
  ansible.builtin.file:
    path: "{{folders}}"
    state: directory
  become: true
  become_user: "{{ansible_user}}"
  vars:
    folders:
    - "{{home_folder}}/mariadb"

- name: Install MariaDB
  become: yes
  become_user: "{{ansible_user}}"
  community.docker.docker_container:
    name: mariadb
    image: mariadb:latest
    state: started
    restart_policy: unless-stopped
    hostname: mariadb
    ports:
      - "3306:3306"
    networks:
      - name: "bridge_to_the_internet"
    env:
      MARIADB_ROOT_USER: "{{mariadb_root_entry.username}}"
      MARIADB_ROOT_PASSWORD: "{{mariadb_root_entry.password}}"
      MARIADB_DATABASE: "poecile"
      MARIADB_USER: "{{mariadb_wordpress_entry.username}}"
      MARIADB_PASSWORD: "{{mariadb_wordpress_entry.password}}"
    volumes:
      - "{{home_folder}}/mariadb:/bitnami/mariadb"

- name: Install PhpMyAdmin
  become: yes
  become_user: "{{ansible_user}}"
  community.docker.docker_container:
    name: phpmyadmin
    image: phpmyadmin:latest
    state: started
    restart_policy: unless-stopped
    hostname: phpmyadmin
    networks:
      - name: "bridge_to_the_internet"
    env:
      PMA_ABSOLUTE_URI: "https://nicolas-delsaux.hd.free.fr/phpmyadmin/"
      PMA_HOST: "mariadb"
      PMA_USER: "{{mariadb_wordpress_entry.username}}"
      PMA_PASSWORD: "{{mariadb_wordpress_entry.password}}"
    labels: 
    # Of course I want to have that container auto-updated
      guerite.update: "{{guerite_crontab}}"
      traefik.enable: "true"
      traefik.http.routers.phpmyadmin.entrypoints: "websecure"
      traefik.http.routers.phpmyadmin.tls: "true"
      traefik.http.routers.phpmyadmin.tls.certresolver: "letsencrypt" 
      traefik.http.routers.phpmyadmin.rule: "Host(`nicolas-delsaux.hd.free.fr`) && PathPrefix(`/phpmyadmin`)"
      traefik.http.routers.phpmyadmin.middlewares: "phpmyadmin@docker"
      traefik.http.middlewares.phpmyadmin-prefix.stripprefix.prefixes: "/phpmyadmin"
      traefik.http.middlewares.phpmyadmin-rewrite-body.plugin.rewritebody.rewrites[0].regex: "\"/"
      traefik.http.middlewares.phpmyadmin-rewrite-body.plugin.rewritebody.rewrites[0].replacement: "\"/phpmyadmin/"
      traefik.http.middlewares.phpmyadmin-rewrite-location.plugin.redirectLocation.default: "true"
      traefik.http.middlewares.phpmyadmin.chain.middlewares: "phpmyadmin-prefix,phpmyadmin-rewrite-location"
    links:
      - mariadb:mariadb

- name: Install Wordpress image
  become: yes
  become_user: "{{ansible_user}}"
  community.docker.docker_container:
    name: poecile
    # https://hub.docker.com/_/wordpress
    image: wordpress:latest
    state: started
    restart_policy: unless-stopped
    hostname: blog
    networks:
      - name: "bridge_to_the_internet"
    env:
      WORDPRESS_BLOG_NAME: "Poecile"
      WORDPRESS_ENABLE_REVERSE_PROXY: "yes"
      WORDPRESS_USERNAME: "{{poecile_entry.username}}"
      WORDPRESS_PASSWORD: "{{poecile_entry.password}}"
      WORDPRESS_EMAIL: "{{poecile_entry.email}}"
      WORDPRESS_FIRST_NAME: "{{poecile_entry.firstname}}"
      WORDPRESS_LAST_NAME: "{{poecile_entry.lastname}}"
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_NAME: poecile
      WORDPRESS_DB_USER: "{{mariadb_wordpress_entry.username}}"
      WORDPRESS_DB_PASSWORD: "{{mariadb_wordpress_entry.password}}"
      # Source - https://stackoverflow.com/a/73492864
      # Posted by Steve x slapps.fr, modified by community. See post 'Timeline' for change history
      # Retrieved 2026-06-07, License - CC BY-SA 4.0

      WORDPRESS_CONFIG_EXTRA: |
        define( 'WP_HOME', 'https://nicolas-delsaux.hd.free.fr/poecile/' );
        define( 'WP_SITEURL', 'https://nicolas-delsaux.hd.free.fr/poecile/' );
        $_SERVER['REQUEST_URI'] = str_replace("/wp-admin/", "/poecile/wp-admin/",  $_SERVER['REQUEST_URI']);

    labels: 
    # Of course I want to have that container auto-updated
      guerite.update: "{{guerite_crontab}}"
      traefik.enable: "true"
      traefik.http.routers.wordpress.entrypoints: "websecure"
      traefik.http.routers.wordpress.tls: "true"
      traefik.http.routers.wordpress.tls.certresolver: "letsencrypt" 
      traefik.http.routers.wordpress.rule: "Host(`nicolas-delsaux.hd.free.fr`) && PathPrefix(`/poecile`)"
      traefik.http.routers.wordpress.middlewares: "wordpress@docker"
      traefik.http.middlewares.wordpress-prefix.stripprefix.prefixes: "/poecile"
      traefik.http.middlewares.wordpress-rewrite-body.plugin.rewritebody.rewrites[0].regex: "\"/"
      traefik.http.middlewares.wordpress-rewrite-body.plugin.rewritebody.rewrites[0].replacement: "\"/poecile/"
      traefik.http.middlewares.wordpress-rewrite-location.plugin.redirectLocation.default: "true"
      traefik.http.middlewares.wordpress.chain.middlewares: "wordpress-prefix,wordpress-rewrite-location"
    volumes:
      - /var/www/html/wordpress/data:/var/www/wordpress/data 
      - /var/www/html/wordpress/plugins/:/var/www/wordpress/plugins/
    links:
      - mariadb:mariadb