- name: Make sure backup folder exists
  file:
    path: {{home_folder}}/{{item}}
    group: nicolas-delsaux
    owner: nicolas-delsaux
    recurse: yes
    state: directory
  with_items:
    - to_backup/rss2imap
    - log

- name: Create crontab entry to backup various configs
  cron:
    name: Backup config
    hour: "0"
    minute: "10"
    job: "rsync -az --copy-links --copy-dirlinks --log-file=~/log/rsync_backup.log ~/to_backup {{ qnap_admin_user }}@{{ qnap_server_address }}:/share/Download/raspberry-server"
  become: yes
  become_user: nicolas-delsaux

